name: 'SchematicUpload'
version: '${version}'
main: 'net.william278.schematicupload.SchematicUpload'
api-version: '1.16'
description: '${description}'
website: 'https://william278.net'
softdepend:
  - WorldEdit
  - FastAsyncWorldEdit
libraries:
  - 'org.eclipse.jetty:jetty-server:${jetty_server_version}'
  - 'org.eclipse.jetty:jetty-servlet:${jetty_servlet_version}'

commands:
  schematicupload:
    usage: '/schematicupload [reload/about]'
    description: 'Upload a schematic'
    aliases: [ 'uploadschematic' ]
  schematicdownload:
    usage: '/schematicdownload <name>'
    description: 'Download a schematic'
    aliases: [ 'downloadschematic' ]

permissions:
  schematicupload.command:
    description: 'Lets you upload schematics'
    default: op
  schematicupload.command.reload:
    description: 'Lets you reload the plugin'
    default: op
  schematicupload.command.about:
    description: 'Lets you view plugin information'
    default: true
  schematicupload.command.download:
    description: 'Lets you download schematics'
    default: true